apiVersion: apps/v1
kind: DaemonSet
metadata:
  name:  {{ .Values.spiderdoctorAgent.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.spiderdoctorAgent.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "project.spiderdoctorAgent.selectorLabels" . | nindent 6 }}
  {{- with .Values.spiderdoctorAgent.updateStrategy }}
  updateStrategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- if or .Values.spiderdoctorAgent.podAnnotations .Values.global.commonAnnotations }}
      annotations:
        {{- if .Values.global.commonAnnotations }}
        {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.spiderdoctorAgent.podAnnotations }}
        {{- include "tplvalues.render" ( dict "value" .Values.spiderdoctorAgent.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "project.spiderdoctorAgent.selectorLabels" . | nindent 8 }}
        {{- if .Values.global.commonLabels }}
        {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.spiderdoctorAgent.podLabels }}
        {{- include "tplvalues.render" ( dict "value" .Values.spiderdoctorAgent.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.spiderdoctorAgent.image.imagePullSecrets }}
      imagePullSecrets:
      {{- with .Values.spiderdoctorAgent.image.imagePullSecrets }}
      {{- toYaml . | trim | nindent 6 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ .Values.spiderdoctorAgent.name | trunc 63 | trimSuffix "-" }}
      priorityClassName: {{ default "system-node-critical" .Values.spiderdoctorAgent.priorityClassName }}
      {{- if .Values.spiderdoctorAgent.hostnetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- else }}
      hostNetwork: false
      dnsPolicy: ClusterFirst
      {{- end }}
      restartPolicy: Always
      {{- with .Values.spiderdoctorAgent.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.spiderdoctorAgent.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.spiderdoctorAgent.affinity }}
      affinity:
      {{- include "tplvalues.render" (dict "value" .Values.spiderdoctorAgent.affinity "context" $) | nindent 6 }}
      {{- else }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
              # Compatible with Kubernetes 1.12.x and 1.13.x
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
      {{- end }}
      containers:
        - name: {{ .Values.spiderdoctorAgent.name | trunc 63 | trimSuffix "-" }}
          image: {{ include "project.spiderdoctorAgent.image" . | quote }}
          imagePullPolicy: {{ .Values.spiderdoctorAgent.image.pullPolicy }}
          command:
            - {{ .Values.spiderdoctorAgent.cmdBinName }}
          args:
            - --config-path=/tmp/config-map/conf.yml
          {{- with .Values.spiderdoctorAgent.extraArgs }}
          {{- toYaml . | trim | nindent 8 }}
          {{- end }}
          {{- if .Values.spiderdoctorAgent.prometheus.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.spiderdoctorAgent.prometheus.port }}
              protocol: TCP
          {{- end }}
          {{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.Version }}
          startupProbe:
            httpGet:
              path: /healthy/startup
              port: {{ .Values.spiderdoctorAgent.httpServer.port }}
              scheme: HTTP
            failureThreshold: {{ .Values.spiderdoctorAgent.httpServer.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.spiderdoctorAgent.httpServer.startupProbe.periodSeconds }}
            successThreshold: 1
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthy/liveness
              port: {{ .Values.spiderdoctorAgent.httpServer.port }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: {{ .Values.spiderdoctorAgent.httpServer.livenessProbe.periodSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.spiderdoctorAgent.httpServer.livenessProbe.failureThreshold }}
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthy/readiness
              port: {{ .Values.spiderdoctorAgent.httpServer.port }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: {{ .Values.spiderdoctorAgent.httpServer.readinessProbe.periodSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.spiderdoctorAgent.httpServer.readinessProbe.failureThreshold }}
            timeoutSeconds: 5
          {{- with .Values.spiderdoctorAgent.resources }}
          resources:
          {{- toYaml . | trim | nindent 12 }}
          {{- end }}
          env:
            - name: ENV_LOG_LEVEL
              value: {{ .Values.spiderdoctorAgent.debug.logLevel | quote }}
            - name: ENV_ENABLED_METRIC
              value: {{ .Values.spiderdoctorAgent.prometheus.enabled | quote }}
            - name: ENV_METRIC_HTTP_PORT
              value: {{ .Values.spiderdoctorAgent.prometheus.port | quote }}
            - name: ENV_HTTP_PORT
              value: {{ .Values.spiderdoctorAgent.httpServer.port | quote }}
            - name: ENV_GOPS_LISTEN_PORT
              value: {{ .Values.spiderdoctorAgent.debug.gopsPort | quote }}
            - name: ENV_GC_REPORT_FOR_DELETED_CRD
              value: {{ .Values.spiderdoctorAgent.gcReport | quote }}
            - name: ENV_AGENT_GRPC_LISTEN_PORT
              value: {{ .Values.spiderdoctorAgent.grpcServer.port | quote }}
            - name: ENV_PATH_AGENT_POD_REPORT
              value: "/report"
            - name: ENV_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ENV_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- with .Values.spiderdoctorAgent.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.spiderdoctorAgent.securityContext }}
          securityContext:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
            - name: config-path
              mountPath: /tmp/config-map
              readOnly: true
            - name: report-data
              mountPath: /report
            {{- if .Values.spiderdoctorAgent.extraVolumes }}
            {{- include "tplvalues.render" ( dict "value" .Values.spiderdoctorAgent.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
      volumes:
        # To read the configuration from the config map
        - name: config-path
          configMap:
            defaultMode: 0400
            name: {{ .Values.global.configName }}
        - name: report-data
          hostPath:
            path: {{ .Values.spiderdoctorAgent.reportHostPath }}
            type: DirectoryOrCreate
      {{- if .Values.spiderdoctorAgent.extraVolumeMounts }}
      {{- include "tplvalues.render" ( dict "value" .Values.spiderdoctorAgent.extraVolumeMounts "context" $ ) | nindent 6 }}
      {{- end }}
